### Họ và Tên: Lâm Quang Phú
### MSSV: 21094601


### Bài 1:
1- Khởi tạo các ma trận tự động theo các yêu cầu sau: \
a. Ma trận A[3,4] toàn giá trị 0 \
b. Ma trận B[2,4] toàn giá trị 1 \
c. Ma trận C[4,4] toàn giá trị 5 \
d. Ma trận D[5,5] với các giá trị trên đường chéo chính là 1 \
e. Ma trận E[4,6] với các giá trị ngẫu nhiên 

In [1]:
import numpy as np

**a. Ma trận A[3,4] toàn giá trị 0**

A = np.zeros((3, 4))
A

**b. Ma trận B[2,4] toàn giá trị 1**

In [3]:
B = np.ones((2, 4))
B 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**c. Ma trận C[4,4] toàn giá trị 5**

In [5]:
C = np.full((4, 4), 5)
C

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

**d. Ma trận D[5,5] với các giá trị trên đường chéo chính là 1**

In [11]:
D = np.identity(5)
D


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**e. Ma trận E[4,6] với các giá trị ngẫu nhiên**

In [26]:
E = np.random.rand(4, 5)
E

array([[0.22220132, 0.13039297, 0.95199855, 0.80431748, 0.22166127],
       [0.28358422, 0.73423465, 0.48134819, 0.50507004, 0.56104142],
       [0.40049137, 0.68857817, 0.74991661, 0.56681212, 0.15400328],
       [0.9196477 , 0.34490013, 0.65552094, 0.8641468 , 0.12685923]])

**2**- Khởi tạo các ma trận vuông A[5,5] toàn giá trị 1 ở đường chéo chính, 0 ở các ô
còn lại một cách tự động. Khởi tạo ma trận vuông B[5,5] toàn giá trị 1 ở các ô là
tổng của 2*i+j (hàng, cột), 0 ở các ô còn lại một cách tự động. Tính bằng tay và tính
tự động các yêu cầu sau: \
a. Tính định thức của A sử dụng thư viện \
b. Tính định thức của B sử dụng thư viện \
c. Tính A*B \
d. Tính A+B \
e. Tính A-B \
f. Tính 4*A/B 

In [33]:
A = np.identity(5)
A

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [75]:
def custom_matrix(row, col):
    my_matrix = np.zeros((row, col))
    for i in range(row):
        for j in range(col):
            if i == j:
                my_matrix[i][j] = 1
    return my_matrix

B = custom_matrix(5, 5)
B

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**a. Tính định thức của A sử dụng thư viện**

In [76]:
print("Định thức của A:", np.linalg.det(A))

Định thức của A: 1.0


**b. Tính định thức của B sử dụng thư viện**

In [77]:
print("Định thức của B:", np.linalg.det(B))

Định thức của B: 1.0


**c. Tính AB**

In [78]:
A.dot(B)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**d. Tính A+B**

In [79]:
A + B

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 2.]])

**e. Tính A-B**

In [80]:
A - B

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**f. Tính 4*A/B**

In [82]:
try:
    B = np.linalg.inv(B)
except:
    print("Không tồn tại ma trận nghịch đảo của B")
else:
    print(4*A.dot(np.linalg.inv(B)))

[[4. 0. 0. 0. 0.]
 [0. 4. 0. 0. 0.]
 [0. 0. 4. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 4.]]


### Bài 2:
Một sọt Cam có 10 trái trong đó có 4 trái hư. Lấy ngẫu nhiên ra ba trái. \
a) Tính xác suất lấy được 3 trái hư. 




In [68]:
from scipy.special import comb

In [69]:
tot_orange = 10
bad_orange = 4
p_3_bad_orange = comb(bad_orange, 3)/comb(tot_orange, 3) # Số cách lấy 3 trái hư/ số cách lấy 3 trái cam
print("Xác suất chọn 3 trái hư khi lấy ngẫu nhiên 3 trái", round(p_3_bad_orange, 4))

Xác suất chọn 3 trái hư khi lấy ngẫu nhiên 3 trái 0.0333


**b) Tính xác suất lấy được 1 trái hư.**

In [70]:
p_1_bad_orange = comb(bad_orange, 1)*comb(tot_orange-bad_orange, 2)/comb(tot_orange, 3) 
# số cách chọn 1 trái hư* số cách chọn 2 trái tốt / số cách chọn 3 trái
print("Xác suất chọn 1 trái hư khi lấy ngẫu nhiên 3 trái", round(p_1_bad_orange, 4))

Xác suất chọn 1 trái hư khi lấy ngẫu nhiên 3 trái 0.5


**c) Tính xác suất lấy được ít nhất một trái hư.**

In [72]:
p_no_bad_orange = comb(tot_orange - bad_orange, 3) / comb(tot_orange, 3) #số cách chọn 3 trái không hư/ số cách chọn 3 trái
p_at_leat_1_bad_orange = 1 - p_no_bad_orange # xác suất chọn ít nhất 1 trái hư = 1 - xác suất số cách chọn không trái nào hư
print("Xác suất chọn được ít nhất 1 trái hư", round(p_at_leat_1_bad_orange, 4))

Xác suất chọn được ít nhất 1 trái hư 0.8333


**d) Tính xác suất lấy được nhiều nhất 2 trái hư.**

In [73]:
# xác suất chọn nhiều nhất 2 trái hư = 1 - xác suất chọn 3 trái hư 
p_at_leat_2_bad_orange = 1 -  p_3_bad_orange
print("Xác suất lấy được nhiều nhất 2 trái hư", round(p_at_leat_2_bad_orange, 4))

Xác suất lấy được nhiều nhất 2 trái hư 0.9667


### Bài 3:
Một gia đình có 10 người con. Giả sử xác suất sinh con trai, con gái như nhau. \
Tính xác suất: \
a) Không có con trai. 



In [83]:
'''
B: Sinh con trai
G: Sinh con gái
theo đề bài:
    P(B) = P(G) = 50%
'''

In [86]:
P_G = 0.5
P_B = 0.5
print("Xác suất không có con trai", P_G) # Xác Không con trai => Xác suất sinh con gái

Xác suất không có con trai 0.5


**b) Có 5 con trai và 5 con gái.**

In [87]:
#Áp dụng phân phối nhị thức
P_5B_and_5G = comb(10, 5)*P_B*pow(P_G, 10-5)
print("Xác suất 5 con trai và 5 con gái", round(P_5B_and_5G, 4))

Xác suất 5 con trai và 5 con gái 3.9375


**c) Số trai từ 5 đến 7.**

In [90]:
from scipy.stats import binom

ImportError: DLL load failed while importing _arpack: The specified procedure could not be found.

In [91]:
#Áp dụng phân phối nhị thức
n = 10
k_values = range(5, 8)
p_5to7_boy = sum([binom.pmf(k, n, P_B) for k in k_values])
print(f"Xác suất có số trai từ 5 đến 7 là:", round(p_5to7_boy, 4))

NameError: name 'binom' is not defined